version: "3"
services:
  api:
    container_name: api
    build:
      context: ./../
      dockerfile: .docker/Dockerfile
    environment:
      - BUILD_MODE=debug # change to debug for debug mode
      - APP_PORT=9000
    ports:
      - "9091:9000"
    volumes:
      - ./../:/usr/src/actix-books-app
    links:
      - mongo
  mongo:
    image: mongo:4.4
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: books
    volumes:
      - data-volume:/data/db
volumes:
  data-volume:
